name: Format

on:
  push:
    branches:
      - main

env:
  FORMATTER_PAT: ${{ secrets.FORMATTER_PAT }}

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # v2 minimum required
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--skip-sorting-imports --replace"
          # Recommended if you use MacOS:
          githubToken: ${{ env.FORMATTER_PAT }}
